export const pino = [
  "src/assets/piano/_ A 0-1.mp3",
  "src/assets/piano/_ A 1-1.mp3",
  "src/assets/piano/_ A 2-1.mp3",
  "src/assets/piano/_ A 3-1.mp3",
  "src/assets/piano/_ A 4-1.mp3",
  "src/assets/piano/_ A 5-1.mp3",
  "src/assets/piano/_ A 6-1.mp3",
  "src/assets/piano/_ A 7-1.mp3",
  "src/assets/piano/_ A#_Bb 0-1.mp3",
  "src/assets/piano/_ A#_Bb 1-1.mp3",
  "src/assets/piano/_ A#_Bb 2-1.mp3",
  "src/assets/piano/_ A#_Bb 3-1.mp3",
  "src/assets/piano/_ A#_Bb 4-1.mp3",
  "src/assets/piano/_ A#_Bb 5-1.mp3",
  "src/assets/piano/_ A#_Bb 6-1.mp3",
  "src/assets/piano/_ A#_Bb 7-1.mp3",
  "src/assets/piano/_ B 0-1.mp3",
  "src/assets/piano/_ B 1-1.mp3",
  "src/assets/piano/_ B 2-1.mp3",
  "src/assets/piano/_ B 3-1.mp3",
  "src/assets/piano/_ B 4-1.mp3",
  "src/assets/piano/_ B 5-1.mp3",
  "src/assets/piano/_ B 6-1.mp3",
  "src/assets/piano/_ B 7-1.mp3",
  "src/assets/piano/_ C 1-1.mp3",
  "src/assets/piano/_ C 2-1.mp3",
  "src/assets/piano/_ C 3-1.mp3",
  "src/assets/piano/_ C 4-1.mp3 ",
  "src/assets/piano/_ C 5-1.mp3 ",
  "src/assets/piano/_ C 6-1.mp3 ",
  "src/assets/piano/_ C 7-1.mp3 ",
  "src/assets/piano/_ C 8-1.mp3 ",
  "src/assets/piano/_ C#_Db 2-1.mp3",
  "src/assets/piano/_ C#_Db 3-1.mp3",
  "src/assets/piano/_ C#_Db 4-1.mp3",
  "src/assets/piano/_ C#_Db 5-1.mp3",
  "src/assets/piano/_ C#_Db 6-1.mp3",
  "src/assets/piano/_ C#_Db 7-1.mp3",
  "src/assets/piano/_ C#_Db-1.mp3 ",
  "src/assets/piano/_ D 1-1.mp3 ",
  "src/assets/piano/_ D 2-1.mp3 ",
  "src/assets/piano/_ D 3-1.mp3 ",
  "src/assets/piano/_ D 4-1.mp3 ",
  "src/assets/piano/_ D 5-1.mp3 ",
  "src/assets/piano/_ D 6-1.mp3 ",
  "src/assets/piano/_ D 7-1.mp3 ",
  "src/assets/piano/_ D#_Eb 1-1.mp3",
  "src/assets/piano/_ D#_Eb 2-1.mp3",
  "src/assets/piano/_ D#_Eb 3-1.mp3",
  "src/assets/piano/_ D#_Eb 4-1.mp3",
  "src/assets/piano/_ D#_Eb 5-1.mp3",
  "src/assets/piano/_ D#_Eb 6-1.mp3",
  "src/assets/piano/_ D#_Eb 7-1.mp3",
  "src/assets/piano/_ E 1-1.mp3 ",
  "src/assets/piano/_ E 2-1.mp3 ",
  "src/assets/piano/_ E 3-1.mp3 ",
  "src/assets/piano/_ E 4-1.mp3 ",
  "src/assets/piano/_ E 5-1.mp3 ",
  "src/assets/piano/_ E 6-1.mp3 ",
  "src/assets/piano/_ E 7-1.mp3 ",
  "src/assets/piano/_ F 1-1.mp3 ",
  "src/assets/piano/_ F 2-1.mp3 ",
  "src/assets/piano/_ F 3-1.mp3 ",
  "src/assets/piano/_ F 4-1.mp3 ",
  "src/assets/piano/_ F 5-1.mp3 ",
  "src/assets/piano/_ F 6-1.mp3 ",
  "src/assets/piano/_ F 7-1.mp3 ",
  "src/assets/piano/_ F#_Gb 1-1.mp3",
  "src/assets/piano/_ F#_Gb 2-1.mp3",
  "src/assets/piano/_ F#_Gb 3-1.mp3",
  "src/assets/piano/_ F#_Gb 4-1.mp3",
  "src/assets/piano/_ F#_Gb 5-1.mp3",
  "src/assets/piano/_ F#_Gb 6-1.mp3",
  "src/assets/piano/_ F#_Gb 7-1.mp3",
  "src/assets/piano/_ G 1-1.mp3 ",
  "src/assets/piano/_ G 2-1.mp3 ",
  "src/assets/piano/_ G 3-1.mp3 ",
  "src/assets/piano/_ G 4-1.mp3 ",
  "src/assets/piano/_ G 5-1.mp3 ",
  "src/assets/piano/_ G 6-1.mp3 ",
  "src/assets/piano/_ G 7-1.mp3 ",
  "src/assets/piano/_ G#_Ab 1-1.mp3",
  "src/assets/piano/_ G#_Ab 2-1.mp3",
  "src/assets/piano/_ G#_Ab 3-1.mp3",
  "src/assets/piano/_ G#_Ab 4-1.mp3",
  "src/assets/piano/_ G#_Ab 5-1.mp3",
  "src/assets/piano/_ G#_Ab 6-1.mp3",
  "src/assets/piano/_ G#_Ab 7-1.mp3",
];
